### ISSUE TITLE
Manual vs Autopilot Control Negotiation During Missions

### ISSUE THREAD

**Issue by ChrisScianna** [ChrisScianna/ROS-Underwater-RnD#135]
When no mission is running the autopilot should not be in control.
When a mission is started the autopilot should take control.
The autopilot should treat the jaus ros bridge issuing an abort, thruster, or fin command as a request to go to manual control and switch control over to manual mode.
The autopilot should not release control just because the jaus ros bridge has connected. This ensures the mission doesn't end as soon as the vehicle surfaces.

**Comment by hidmic** [comment]
A typical approach to manual overrides in ROS is to use a multiplexer with priorities. This multiplexer sits in between control systems, teleoperation apps, and the driver nodes, relaying messages from the highest priority source. The [`cmd_vel_mux` package](https://github.com/kobuki-base/cmd_vel_mux) is pretty ubiquitous. 

With that in mind, I propose we rework the system a bit to use this pattern. That is to:

- [ ] Develop a mux for thruster and fin commands.
    - The low priority source will be the `mission_control` -> `autopilot` subsystem.
    - The high priority input will be the OCU -> `jaus_ros_bridge` subsystem.
- [ ] Remove manual control flags from `autopilot`, `jaus_ros_bridge`, and OCU.
   - No need to be explicit, publishing thruster or fin commands will force a switch.
   - Mux can publish which input is in control i.e. active.
- [ ] Replace `mission_control` heartbeat with activity in setpoint topics (i.e. periodic republishing).
   - If `mission_control` is idle OR it dies, no setpoint will be published, autopilot will know it has to take 
     the vehicle to surface.
- [ ] Change OCU to wait for mission completion.
   - It takes over right away right now, not letting missions complete, not letting logging end.
   - Proper timeouts in missions, `mission_control` and OCU can ensure there's no risk to block indefinitely.

@ChrisScianna thoughts? I think having `mission_control` "own" the `autopilot` like this would simplify things.

**Comment by ChrisScianna** [comment]
This looks good. I think the current control flags do handle the mission complete/cancel mission activities so we will want to make sure that the mission control and OCU are still talking to each other about making sure to cancel the mission. I could see the OCU commanding the thruster for 10 seconds then the mission taking back over if we dont implement it a certain way.

**Comment by hidmic** [comment]
> I could see the OCU commanding the thruster for 10 seconds then the mission taking back over if we dont implement it a certain way.

Definitely. It'd be on the OCU to make sure to abort the mission (and wait for it to complete the abort). Thinking out loud, maybe we shouldn't be treating `abort` as if it was a `cancel` request. Maybe `abort` should result in `mission_control` dropping the mission entirely. No questions asked.

**Comment by patapufate** [comment]
During the testing of #151 that works on this ticket, I have found that the Jaus ROS Bridge and autopilot use different topics for publishing commands to the fin_control (angles). This could cause the messages received by the fin_control node to overlap.

- Jaus Ros Bridge [publishes on](https://github.com/ChrisScianna/ROS-Underwater-RnD/blob/dbe757ea141edc860b011e86bb1854b5b12e9131/jaus_ros_bridge/src/SetFinDeflection.cpp#L51)  * fin_control/set_angle * topic. The JRB node receives 4 messages from the OCU

- The Autopilot [publishes on](https://github.com/ChrisScianna/ROS-Underwater-RnD/blob/dbe757ea141edc860b011e86bb1854b5b12e9131/autopilot/src/autopilot.cpp#L136)  * fin_control/set_angles * topic.

Chris. Is it possible that the OCU sends 1 msg with the 4 angles and then Jaus ROS Bridge publishes it on the “fin_control/set_angles” topic?

**Comment by ChrisScianna** [comment]
You are spot on. The OCU used to have the functionality of changing one fin at a time and not all four so it used the set_angle option and the autopilot would always control all 4 always. We can update the JausRosBridge to send the set_angles instead and wait until it gets an update for all 4 fins or allow the set_angles topic on the fin_control side have a nan option to not change a fin.

**Comment by hidmic** [comment]
> We can update the JausRosBridge to send the set_angles instead and wait until it gets an update for all 4 fins or allow the set_angles topic on the fin_control side have a nan option to not change a fin.

@ChrisScianna those are reasonable workarounds, but what about dropping this per fin servo interface entirely (i.e. changing the OCU to use the same interface that the autopilot does)?

**Comment by ChrisScianna** [comment]
I'm planning a more over arching update to the comms protocol between the OCU and the vehicle and we can fix it then. It will line up with a transition to a COTS GUI that we would like to make a plug in for on the Windows side.

**Comment by patapufate** [comment]
> > I could see the OCU commanding the thruster for 10 seconds then the mission taking back over if we dont implement it a certain way.
> 
> Definitely. It'd be on the OCU to make sure to abort the mission (and wait for it to complete the abort). Thinking out loud, maybe we shouldn't be treating `abort` as if it was a `cancel` request. Maybe `abort` should result in `mission_control` dropping the mission entirely. No questions asked. Following that train of thought, we could have `mission_control` abort (hard) if the mux says the OCU is in control.

Continuing with this thread

When the Jaus ROS Bridge receives the command to change to "Manual Mode" (from the OCU), it publishes on the `/jaus_ros_bridge/activate_manual_control` [topic](https://github.com/ChrisScianna/ROS-Underwater-RnD/blob/ffb31699fc0a8d3e8ce35eda7670bda43060d86e/jaus_ros_bridge/src/JausDataManager.cpp#L85). This topic is only being subscribed by the autopilot, therefore, mission contol won't cancel/abort the mission. The mission control will only aborts/cancels the mission if it receives a message from the Jaus ROS Bridge on the `abort_mission` [topic](https://github.com/ChrisScianna/ROS-Underwater-RnD/blob/ffb31699fc0a8d3e8ce35eda7670bda43060d86e/mission_control/src/mission_control.cpp#L242)
For the foregoing reasons, we should change this behavior. Our options are:

1. Modifying the OCU to disable the ListView object (Manual/Mission Control) when the mission is running and enable it on the _click event_ in the _Start/Stop Mission button_.
2. Modifying OCU to send an abort command to the mission control before sending the _activate manual control_ command.
3. We could send an abort message to the mission control when the Jaus ROS Bridge receive a Manual Control Command [here](https://github.com/ChrisScianna/ROS-Underwater-RnD/blob/ffb31699fc0a8d3e8ce35eda7670bda43060d86e/jaus_ros_bridge/src/JausDataManager.cpp#L163)
4. Mission Control could subscribe to the `/jaus_ros_bridge/activate_manual_control` and aborts the current mission.

@hidmic, @ChrisScianna thoughts?

**Comment by hidmic** [comment]
It's @ChrisScianna's call, but IMHO, since the mux removes the need for an explicit manual control activation (publishing thruster and fin commands directly will do), the OCU should do something like (2). That is, to have logic to realize a mission is running and update the UI accordingly, as well as to wait for the mission to complete after issuing an abort command. 

Thinking out loud, we also probably need a way to tell `mission_control` to just drop everything and go idle (as opposed to executing the abort behavior it executes now). With that and a timeout we can afford an emergency button in the OCU.

**Comment by hidmic** [comment]
@patapufate BTW, I just recalled why step 3 in https://github.com/ChrisScianna/ROS-Underwater-RnD/issues/135#issuecomment-846155333 was necessary. It is an alternative to the back and forth between the `mission_control` and `autopilot`. Right now, the `autopilot` has to monitor `mission_control` liveliness and mission status to drop setpoints. Periodically published setpoints would remove that need.

**Comment by hidmic** [comment]
Alright, the bulk of this work was done. We can follow-up with improvements later on. Closing!
