### ISSUE TITLE
Relocate ROS publisher creation in vectornav node 

### ISSUE THREAD

**Issue by hidmic** [ChrisScianna/ROS-Underwater-RnD#137]
### Rationale

The `vectornav` node [sets up](https://github.com/ChrisScianna/ROS-Underwater-RnD/blob/2636dcc932aa46be359729baaa5fc546ddd01787/vectornav/src/main.cpp#L321-L383) ROS publishers and subscribers before it has successfully connected to the device, which may involve [several attempts](https://github.com/ChrisScianna/ROS-Underwater-RnD/blob/2636dcc932aa46be359729baaa5fc546ddd01787/vectornav/src/main.cpp#L409-L449). As a result, we often get spurious publisher staling faults on bringup. 

We have to defer publisher creation till after we've managed to connect.

### Definition of Done

- [x] Rearrange `vectornav`'s node `run` function to avoid these faults.
- [x] Bump pose estimator staling checks to cope with these setup delays.
- [x] Validate all changes manually on a vehicle.

**Comment by patapufate** [comment]
Fixed in #139
