### ISSUE TITLE
Mission Logs Missing

### ISSUE THREAD

**Issue by ChrisScianna** [ChrisScianna/ROS-Underwater-RnD#142]
When running many consecutive short (~20 second) missions ~65% of missions were not logged. This may be because of a delay in the start of logging or a delay in the previous log finishing.

**Comment by hidmic** [comment]
This is definitely an issue with `bag_mission_recorder`. Maybe it's too slow, as you say, though 20 seconds is a long time to end up not grabbing anything. We have to investigate.

**Comment by hidmic** [comment]
To fix this, I think merging `mission_logger` functionality into `mission_control` is best. Or at least it'll make it easier to control. It's more or less straightforward to start a thread to record a bagfile. Text logging is trickier, perhaps the [`ros_type_introspection`](https://github.com/facontidavide/ros_type_introspection) package can help.

@ChrisScianna thoughts?

**Comment by ChrisScianna** [comment]
Now that we have the plot juggler set up for us, we can move away from the text files.

**Comment by hidmic** [comment]
Alright, now that we have the `LogToBagfile` decorator, bag file recording delays should no longer be a problem.

@ChrisScianna let's give it a shot for a real mission. If it works, we can drop the `mission_logger` package.

**Comment by hidmic** [comment]
Already addressed, closing!
