### ISSUE TITLE
Final mission behavior

### ISSUE THREAD

**Issue by ChrisScianna** [ChrisScianna/ROS-Underwater-RnD#144]
Twice out of ~40 runs resulted in the final behavior not ending. 

Final behavior:
```
<ForceSuccess>
  <Timeout msec="5000">
    <Action ID="AttitudeServo" pitch="-39" pitch-tolerance="0.0" pitch-units="degrees" roll="0" roll-tolerance="0.0" roll-units="degrees" speed_knots="5.0" yaw="0.0" yaw-tolerance="0.0" yaw-units="degrees"/>
  </Timeout>
</ForceSuccess>
```

**Comment by hidmic** [comment]
Hmm, tolerance is pretty tight. Also, this looks like an `Abort` behavior replacement?

**Comment by ChrisScianna** [comment]
Basically the same as an abort but gives it some thrust to get to the surface with.

**Comment by hidmic** [comment]
So, assuming that we don't have other convention issues like the one described in #141 and that a -39 degrees vehicle pitch is achievable, the problem might be that tolerances are too tight and that we are fixing setpoints we don't care about. Something like:

```
<ForceSuccess>
  <Timeout msec="5000">
    <Action ID="AttitudeServo" pitch="-39.0" pitch-tolerance="1.0" pitch-units="degrees" speed_knots="5.0"/>
  </Timeout>
</ForceSuccess>
```

would solve those.

**Comment by ChrisScianna** [comment]
It was more meant as a pitch up as much as possible for 5 seconds to surface not a get to a 39 degree upward pitch. The issue I'm having is that it either doesn't finish the mission or it does and doesn't change the behavior after finishing the mission to the no thruster fins up pose.

**Comment by hidmic** [comment]
I see. 

> It was more meant as a pitch up as much as possible for 5 seconds to surface not a get to a 39 degree upward pitch.

`AttitudeServo` will try to servo fins to match the attitude set. If the timeout doesn't timeout, that's something we definitely have to look into.

> or it does and doesn't change the behavior after finishing the mission to the no thruster fins up pose.

`mission_control` won't shut down the thruster on its own if no action does so. I think we need to settle a clear chain of command as part of #135.

**Comment by ChrisScianna** [comment]
I believe fixing up the manual vs autopilot will fix this. The autopilot has in the past turned off the thruster and pointed the fins up when mission completion occurred.
