### ISSUE TITLE
Default GPS values in /state

### ISSUE THREAD

**Issue by ChrisScianna** [ChrisScianna/ROS-Underwater-RnD#158]
The GPS provides an nan in the latitude and longitude fields when it has had a GPS fix then losses it. This makes it's way through the /state topic as nan. Before the GPS gets a fix, it doesn't provide anything and the /state defaults to 0. I suggest we have the /state default to nan to have uniformity between no fix states.

**Comment by hidmic** [comment]
Closing as it's been done for a week now!
